# Generated by Django 3.0.14 on 2022-05-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_auto_20220518_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
